### ISSUE TITLE
Update database table schema

### ISSUE THREAD

**Issue by dlowrey** [NilsG-S/team-null-back-end#3]
The database schema needs to be created and used in the `initdb.py` database set up.

**Comment by NilsG-S** [comment]
Hospital

- Appointments
- Employees
- Patients
- Reports
- Invoices
- Payments

Employees

- UID
- Name
- Position
- Associated with

Appointment

- Doctor UID
- Patient UID
- Date/Time
- No-show
- Treatment record UID
- Invoice amount
- Copay amount

Patient

- UID
- Name
- Address
- Phone number
- Email
- Social security number
- Insurance name

Treatment Record

- UID
- Reason
- Weight
- Height
- Blood pressure
- Doctor’s treatment content
- Prescription

Payment

- UID (for receipt)
- Patient UID
- Date
- Time
- Category (invoice, copay)
- Method (credit, debit)
- Reference number (validation from company, null for cash/check)
- Amount

Reports

- Date
- Type (monthly vs daily)
- Number of patients served
- Healthcare income
- Doctor UID

**Comment by dlowrey** [comment]
Tables set up in Databse/README.md and initdb.py
