### ISSUE TITLE
Initialize Database with Data for Testing

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/team-null-back-end#5]
We need to initialize the database with a CEO, doctors, nurses, staff, and patients for testing the front end. It would make things difficult if @joyellealina and I needed to create a new user each time we started the testing server.

**Comment by dlowrey** [comment]
@NilsG-S @joyellealina, We have finished setting up the script `initdb.py` to set up the database and the tables. If you would like, you can create a `.csv` file with the columns and order matching any of the tables in `Database/README.md`, and fill out any user info you would like in it. Then send it to me and I will put it in the `initdb.py` script to fill in the tables in the database for your use. Just make sure the columns are in the same order they appear in the actual table so I won't have to mess with it a ton.

**Comment by dlowrey** [comment]
@NilsG-S, @joyellealina : @IntJRG and I will write the API to insert data first and get it to you guys as soon as possible so you can start inserting data.

**Comment by dlowrey** [comment]
@NilsG-S @joyellealina @IntJRG  I have included sql scripts to insert data into the tables in Database/dummy-data.sql. You can open these files in workbench and run them, make sure you have the healthcaredb selected as the database to use.
