### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/team-null-back-end#6]
Are we going to have a proper authentication system, or just mock it up?

**Comment by dlowrey** [comment]
Authentication will be handled server side via login with employee ID and employee password. The password will be hashed and salted and stored in the database in the employees table. Authentication feature will be implemented last.

**Comment by dlowrey** [comment]
Still need to address this

**Comment by dlowrey** [comment]
@NilsG-S what are you thinking about this?

**Comment by NilsG-S** [comment]
@dlowrey How are you doing on time? If you feel like you can, I would say we should go ahead and put a password field in the employee table, it doesn't even have to be hashed/salted.

**Comment by dlowrey** [comment]
@IntJRG 

@NilsG-S and I were discussing this. We have decided that the employees will log in with their `id` and `password`.

What you need to do is:

- create a branch `login-auth` and check it out (make sure you are on `master` and you have pulled before doing this)
-  add a `password` column to the `employees`
- create a `/src/Auth` folder where we will have a `login` endpoint that will take in an `id` and a `password` and will return the `employee` object if they match a record in the `employee` table and set status to `200` and an empty object with status `401` if they don't.

@NilsG-S will update the wiki with this endpoint soon for your reference.

**Comment by IntJRG** [comment]
@NilsG-S @dlowrey 

I've done all of the above now. Sorry it took so long.

**Comment by dlowrey** [comment]
solved by #29
